id = "cursor-dark-theme"
name = "Cursor Dark Themes"
version = "0.0.1"
schema_version = 2
authors = ["LooSheng", "Cursor Editor Team"]
description = "Themes transplanted from cursor editor"
repository = "https://github.com/loosheng/zed-cursor-dark"
